
management:
  endpoint:
    shutdown:
      enabled: true
    quartz:
      enabled: false
    beans:
      cache:
        time-to-live: 1h
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: logger
      cors:
        allowed-origins: http://localhost:8080
        allowed-methods: GET